// 검색 결과 탭바 메뉴
export const SEARCH_TAB_MENU_LIST = [
  { content: "글", param: "POST" },
  { content: "블로그", param: "BLOG" },
];

// 검색 결과 더미 데이터
export const DUMMY_POST_RESULT_LIST = [
  {
    profileImg: "/profileImg1.png",
    nickname: "사용자1",
    createAt: "2024-09-24 15:08",
    title: "게시글 제목1",
    content:
      "게시글 내용1게시글 내용1게시글 내용1게시글 내용1게시글 내용1게시글 내용1게시글 내용1게시글 내용1게시글 내용1게시글 내용1게시글 내용1게시글 내용1게시글 내용1게시글 내용1게시글 내용1게시글 내용1",
    thumbnail: "img",
    likes: 123,
    comments: 456,
    views: 1234,
    codeId: 12,
  },
  {
    profileImg: "/profileImg2.png",
    nickname: "사용자2",
    createAt: "2024-09-24 15:08",
    title: "게시글 제목2",
    content: "게시글 내용2",
    thumbnail: "",
    likes: 123,
    comments: 456,
    views: 1234,
  },
  {
    profileImg: "/profileImg3.png",
    nickname: "사용자3",
    createAt: "2024-09-24 15:08",
    title: "게시글 제목3",
    content: "게시글 내용3",
    thumbnail: "",
    likes: 123,
    comments: 456,
    views: 1234,
    codeId: 13,
  },
  {
    profileImg: "/profileImg4.png",
    nickname: "사용자4",
    createAt: "2024-09-24 15:08",
    title: "게시글 제목4",
    content: "게시글 내용4",
    thumbnail: "img",
    likes: 123,
    comments: 456,
    views: 1234,
    codeId: 14,
  },
  {
    profileImg: "/profileImg5.png",
    nickname: "사용자5",
    createAt: "2024-10-09 17:08",
    title: "게시글 제목5",
    content: "게시글 내용5",
    thumbnail: "",
    likes: 123,
    comments: 456,
    views: 1234,
  },
  {
    profileImg: "/profileImg1.png",
    nickname: "사용자1",
    createAt: "2024-09-24 15:08",
    title: "게시글 제목1",
    content: "게시글 내용1",
    thumbnail: "",
    likes: 123,
    comments: 456,
    views: 1234,
    codeId: 12,
  },
  {
    profileImg: "/profileImg2.png",
    nickname: "사용자2",
    createAt: "2024-09-24 15:08",
    title: "게시글 제목2",
    content: "게시글 내용2",
    thumbnail: "img",
    likes: 123,
    comments: 456,
    views: 1234,
  },
  {
    profileImg: "/profileImg3.png",
    nickname: "사용자3",
    createAt: "2024-09-24 15:08",
    title: "게시글 제목3",
    content: "게시글 내용3",
    thumbnail: "img",
    likes: 123,
    comments: 456,
    views: 1234,
    codeId: 13,
  },
  {
    profileImg: "/profileImg4.png",
    nickname: "사용자4",
    createAt: "2024-09-24 15:08",
    title: "게시글 제목4",
    content: "게시글 내용4",
    thumbnail: "",
    likes: 123,
    comments: 456,
    views: 1234,
    codeId: 14,
  },
  {
    profileImg: "/profileImg5.png",
    nickname: "사용자5",
    createAt: "2024-10-09 17:08",
    title: "게시글 제목5",
    content: "게시글 내용5",
    thumbnail: "img",
    likes: 123,
    comments: 456,
    views: 1234,
  },
];

export const DUMMY_BLOG_RESULT_LIST = [
  {
    id: 0,
    nickname: "사용자123",
    profileImg: "/profileImg1.png",
    status: "안녕하세요 개발자를 준비하고 있는 사용자123입니다! 잘 부탁드려요!",
  },
  {
    id: 1,
    nickname: "사용자123",
    profileImg: "/profileImg2.png",
    status: "안녕하세요 개발자를 준비하고 있는 사용자123입니다! 잘 부탁드려요!",
  },
  {
    id: 2,
    nickname: "사용자123",
    profileImg: "/profileImg3.png",
    status: "안녕하세요 개발자를 준비하고 있는 사용자123입니다! 잘 부탁드려요!",
  },
  {
    id: 3,
    nickname: "사용자123",
    profileImg: "/profileImg4.png",
    status: "안녕하세요 개발자를 준비하고 있는 사용자123입니다! 잘 부탁드려요!",
  },
  {
    id: 4,
    nickname: "사용자123",
    profileImg: "/profileImg5.png",
    status: "안녕하세요 개발자를 준비하고 있는 사용자123입니다! 잘 부탁드려요!",
  },
  {
    id: 5,
    nickname: "사용자123",
    profileImg: "/profileImg6.png",
    status: "안녕하세요 개발자를 준비하고 있는 사용자123입니다! 잘 부탁드려요!",
  },
  {
    id: 6,
    nickname: "사용자123",
    profileImg: "/profileImg1.png",
    status: "안녕하세요 개발자를 준비하고 있는 사용자123입니다! 잘 부탁드려요!",
  },
  {
    id: 7,
    nickname: "사용자123",
    profileImg: "/profileImg2.png",
    status: "안녕하세요 개발자를 준비하고 있는 사용자123입니다! 잘 부탁드려요!",
  },
  {
    id: 8,
    nickname: "사용자123",
    profileImg: "/profileImg3.png",
    status: "안녕하세요 개발자를 준비하고 있는 사용자123입니다! 잘 부탁드려요!",
  },
  {
    id: 9,
    nickname: "사용자123",
    profileImg: "/profileImg4.png",
    status: "안녕하세요 개발자를 준비하고 있는 사용자123입니다! 잘 부탁드려요!",
  },
  {
    id: 10,
    nickname: "사용자123",
    profileImg: "/profileImg5.png",
    status: "안녕하세요 개발자를 준비하고 있는 사용자123입니다! 잘 부탁드려요!",
  },
  {
    id: 11,
    nickname: "사용자123",
    profileImg: "/profileImg6.png",
    status: "안녕하세요 개발자를 준비하고 있는 사용자123입니다! 잘 부탁드려요!",
  },
  {
    id: 12,
    nickname: "사용자123",
    profileImg: "/profileImg1.png",
    status: "안녕하세요 개발자를 준비하고 있는 사용자123입니다! 잘 부탁드려요!",
  },
  {
    id: 13,
    nickname: "사용자123",
    profileImg: "/profileImg2.png",
    status: "안녕하세요 개발자를 준비하고 있는 사용자123입니다! 잘 부탁드려요!",
  },
  {
    id: 14,
    nickname: "사용자123",
    profileImg: "/profileImg3.png",
    status: "안녕하세요 개발자를 준비하고 있는 사용자123입니다! 잘 부탁드려요!",
  },
  {
    id: 15,
    nickname: "사용자123",
    profileImg: "/profileImg4.png",
    status: "안녕하세요 개발자를 준비하고 있는 사용자123입니다! 잘 부탁드려요!",
  },
  {
    id: 16,
    nickname: "사용자123",
    profileImg: "/profileImg5.png",
    status: "안녕하세요 개발자를 준비하고 있는 사용자123입니다! 잘 부탁드려요!",
  },
  {
    id: 17,
    nickname: "사용자123",
    profileImg: "/profileImg6.png",
    status: "안녕하세요 개발자를 준비하고 있는 사용자123입니다! 잘 부탁드려요!",
  },
  {
    id: 18,
    nickname: "사용자123",
    profileImg: "/profileImg1.png",
    status: "안녕하세요 개발자를 준비하고 있는 사용자123입니다! 잘 부탁드려요!",
  },
  {
    id: 19,
    nickname: "사용자123",
    profileImg: "/profileImg2.png",
    status: "안녕하세요 개발자를 준비하고 있는 사용자123입니다! 잘 부탁드려요!",
  },
];
